/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this SecretBackendConnection
func (mg *SecretBackendConnection) GetTerraformResourceType() string {
	return "vault_database_secret_backend_connection"
}

// GetConnectionDetailsMapping for this SecretBackendConnection
func (tr *SecretBackendConnection) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"cassandra[*].password": "spec.forProvider.cassandra[*].passwordSecretRef", "cassandra[*].pem_bundle": "spec.forProvider.cassandra[*].pemBundleSecretRef", "cassandra[*].pem_json": "spec.forProvider.cassandra[*].pemJsonSecretRef", "couchbase[*].base64_pem": "spec.forProvider.couchbase[*].base64PemSecretRef", "couchbase[*].password": "spec.forProvider.couchbase[*].passwordSecretRef", "elasticsearch[*].password": "spec.forProvider.elasticsearch[*].passwordSecretRef", "hana[*].password": "spec.forProvider.hana[*].passwordSecretRef", "influxdb[*].password": "spec.forProvider.influxdb[*].passwordSecretRef", "influxdb[*].pem_bundle": "spec.forProvider.influxdb[*].pemBundleSecretRef", "influxdb[*].pem_json": "spec.forProvider.influxdb[*].pemJsonSecretRef", "mongodb[*].password": "spec.forProvider.mongodb[*].passwordSecretRef", "mongodbatlas[*].private_key": "spec.forProvider.mongodbatlas[*].privateKeySecretRef", "mssql[*].password": "spec.forProvider.mssql[*].passwordSecretRef", "mysql[*].password": "spec.forProvider.mysql[*].passwordSecretRef", "mysql[*].tls_certificate_key": "spec.forProvider.mysql[*].tlsCertificateKeySecretRef", "mysql_aurora[*].password": "spec.forProvider.mysqlAurora[*].passwordSecretRef", "mysql_legacy[*].password": "spec.forProvider.mysqlLegacy[*].passwordSecretRef", "mysql_rds[*].password": "spec.forProvider.mysqlRds[*].passwordSecretRef", "oracle[*].password": "spec.forProvider.oracle[*].passwordSecretRef", "postgresql[*].password": "spec.forProvider.postgresql[*].passwordSecretRef", "redis[*].password": "spec.forProvider.redis[*].passwordSecretRef", "redis_elasticache[*].password": "spec.forProvider.redisElasticache[*].passwordSecretRef", "redis_elasticache[*].username": "spec.forProvider.redisElasticache[*].usernameSecretRef", "redshift[*].password": "spec.forProvider.redshift[*].passwordSecretRef", "snowflake[*].password": "spec.forProvider.snowflake[*].passwordSecretRef"}
}

// GetObservation of this SecretBackendConnection
func (tr *SecretBackendConnection) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this SecretBackendConnection
func (tr *SecretBackendConnection) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this SecretBackendConnection
func (tr *SecretBackendConnection) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this SecretBackendConnection
func (tr *SecretBackendConnection) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this SecretBackendConnection
func (tr *SecretBackendConnection) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this SecretBackendConnection using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *SecretBackendConnection) LateInitialize(attrs []byte) (bool, error) {
	params := &SecretBackendConnectionParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *SecretBackendConnection) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this SecretBackendRole
func (mg *SecretBackendRole) GetTerraformResourceType() string {
	return "vault_database_secret_backend_role"
}

// GetConnectionDetailsMapping for this SecretBackendRole
func (tr *SecretBackendRole) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this SecretBackendRole
func (tr *SecretBackendRole) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this SecretBackendRole
func (tr *SecretBackendRole) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this SecretBackendRole
func (tr *SecretBackendRole) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this SecretBackendRole
func (tr *SecretBackendRole) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this SecretBackendRole
func (tr *SecretBackendRole) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this SecretBackendRole using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *SecretBackendRole) LateInitialize(attrs []byte) (bool, error) {
	params := &SecretBackendRoleParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *SecretBackendRole) GetTerraformSchemaVersion() int {
	return 0
}
